### PR TITLE
fix unwanted shallow copy in ProjDataInMemory

### LINKED ISSUE #408: ProjDataInMemory copy constructor not performing deep copy
the following code:
```
// Get original sino
const ProjDataInMemory proj_data(*ProjData::read_from_file("/home/rich/Documents/Data/sino_to_fwd.hs"));
std::cout << "\nmax in input sino = " << get_max(proj_data) << "\n";

// Copy
ProjDataInMemory copy = proj_data;
std::cout << "max in copied sino = " << get_max(copy) << "\n";

// Fill copy
copy.fill(1.f);
std::cout << "max in filled sino = " << get_max(copy) << "\n";

// Print max in original
std::cout << "max in input sino = " << get_max(proj_data) << "\n";
```
gives the following output:
```
max in input sino = 7.25579e+07
max in copied sino = 7.25579e+07
max in filled sino = 1
max in input sino = 1
```
i.e., the original sinogram (marked `const`) is modified. 

This is because the default copy constructor simply copies the `shared_ptr` of the stream as opposed to creating a new stream.

### PR DESCRIPTION
**Pull request by rijobro**
fixes #408

### CODE REVIEW

**Comment by rijobro** [comment]
Sorry, accidentally closed this one. Should explain the strange diffs in the GPU PR, #355.

File: src/buildblock/ProjDataInMemory.cxx [hunk 1]
```diff
@@ -88,34 +88,54 @@ ProjDataInMemory(shared_ptr<ExamInfo> const& exam_info_sptr,
...
-ProjDataInMemory(const ProjData& proj_data)
-  : ProjDataFromStream(proj_data.get_exam_info_sptr(),
-		       proj_data.get_proj_data_info_ptr()->create_shared_clone(), shared_ptr<iostream>())
+static
+shared_ptr<std::iostream>
+create_stream()
 {
+  shared_ptr<std::iostream> output_stream_sptr;
 #ifdef STIR_USE_OLD_STRSTREAM
   const size_t buffer_size = get_size_of_buffer();
```
Comment (KrisThielemans) [inline src/buildblock/ProjDataInMemory.cxx]: actually a call to a member? I guess can't have it as `static`

Comment (rijobro) [reply src/buildblock/ProjDataInMemory.cxx]: Ok, no longer static. If you're happy and Travis is happy, I guess this can be merged.
