### PR TITLE
Fix ML_norm bug and add tests

### LINKED ISSUE #948: ML_norm is broken since #833
#833 introduced capabilities for virtual crystals in the ML norm code. Unfortunately, the logic to find the gaps was incorrect.

PR coming

### PR DESCRIPTION
**Pull request by KrisThielemans**
Fixes #948.

also add some C++ tests, and run `find_ML_norm_tests.sh` on Travis (sadly we made that test, but forgot to run it!)

### CODE REVIEW

File: src/test/test_ML_norm.cxx [hunk 1]
```diff
@@ -0,0 +1,183 @@
...
+  \brief Test program for ML_norm.h functionality
+
+  \author Kris Thielemans
+
+*/
+/*
+    Copyright (C) 2021, University College London
+    This file is part of STIR.
+
+    SPDX-License-Identifier: Apache-2.0 AND License-ref-PARAPET-license
```
Comment (KrisThielemans) [inline src/test/test_ML_norm.cxx:17]:
```suggestion
    SPDX-License-Identifier: Apache-2.0
```
