### PR TITLE
This code might handle comparisons of floats over large scales, in a better way. 

### LINKED ISSUE #183: RunTests::check_if_equal unsafe for floats/double
current code uses
```c++
((fabs(b)>tolerance && fabs(a/b-1) > tolerance)
      || (fabs(b)<=tolerance && fabs(a-b) > tolerance))
```
However, this fails if `tolerance` is large, e.g. for large magnitude numbers, as `fabs(a/b/-1)` should always be small.

### PR DESCRIPTION
**Pull request by NikEfth**
Absolute and relative comparison, avoiding divisions, the tolerance is applied on the largest on the two numbers. closes #183

### CODE REVIEW

File: src/include/stir/RunTests.h [hunk 1]
```diff
@@ -353,8 +353,15 @@ bool RunTests::check(const bool result, const std::string& str)
 bool
 RunTests::check_if_equal(const double a, const double b, const std::string& str)
 {
-  if ((fabs(b)>tolerance && fabs(a/b-1) > tolerance)
-      || (fabs(b)<=tolerance && fabs(a-b) > tolerance))
+    double diff = fabs(b-a);
```
Comment (KrisThielemans) [inline src/include/stir/RunTests.h]: `const double`

File: src/include/stir/RunTests.h [hunk 2]
```diff
@@ -353,8 +353,15 @@ bool RunTests::check(const bool result, const std::string& str)
...
+    if (diff <= tolerance)
+            return true;
+
+    double _a = fabs(a);
+    double _b = fabs(b);
+    float largest = (_b > _a) ? _b : _a;
```
Comment (KrisThielemans) [inline src/include/stir/RunTests.h]: `double`, but why not use `std::max(fabs(a),fabs(b))`. far simpler

**Comment by KrisThielemans** [comment]
I'm a bit torn on this. the first test on `fabs(a-b)` uses a tolerance which is "absolute", while the second one is a relative one. In many cases, it won't make sense to have these to be the same.

I feel we should probably split this into 2 functions, one with a relative tolerance, and one with an absolute one. Or probably better: have 2 tolerances, a relative and an absolute one. Should we then satisfy both?

All this needs some checking of current tests on what they expect.

**Comment by NikEfth** [comment]
I did some tests over many different ranges to come up with this formula. I was unsure where such test function would fit the best, if you would like to have it. Having two does not make sense to me, because the comparison function should be agnostic to the comparison.

**Comment by NikEfth** [comment]
`Error: Failed to download resource "gcc"`
